#!/usr/bin/env bun
/**
 * Automated API Documentation Generator
 * 
 * This script generates API documentation from TypeScript source code and TSDoc comments.
 * It parses source files using regex to extract public exports and their TSDoc comments.
 * 
 * Generated files are placed in docs/generated-api/ and should not be manually edited.
 * 
 * @remarks
 * - Source code is the source of truth
 * - TSDoc comments are extracted from public exports
 * - TypeScript type information is included
 * - Generated files include a notice header
 */

import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// ============================================================================
// Configuration
// ============================================================================

const CONFIG = {
  entryPoint: path.join(process.cwd(), "src/index.ts"),
  outputDir: path.join(process.cwd(), "docs/generated-api"),
  generatedNotice: `> **This file is automatically generated. Do not edit manually.**
> 
> Generated by: \`bun run docs:api\`
> Source: TypeScript source code and TSDoc comments
> Last updated: ${new Date().toISOString()}
`,
  excludePatterns: [/^_/, /^internal/],
} as const;

// ============================================================================
// Type Definitions
// ============================================================================

interface ApiSymbol {
  name: string;
  kind: string;
  filePath: string;
  description?: string;
  tsdoc?: TSDoc;
  type?: string;
  signature?: string;
  parameters?: Parameter[];
  returnType?: string;
  typeParameters?: TypeParameter[];
  isExported: boolean;
  isPublic: boolean;
  category: "core" | "api";
  subcategory?: string;
}

interface TSDoc {
  summary?: string;
  remarks?: string;
  examples?: string[];
  params?: ParamTag[];
  returns?: string;
  see?: string[];
  deprecated?: string;
  template?: string[];
}

interface ParamTag {
  name: string;
  description: string;
}

interface Parameter {
  name: string;
  type: string;
  description?: string;
  isOptional: boolean;
}

interface TypeParameter {
  name: string;
  constraint?: string;
  default?: string;
}

interface ApiMetadata {
  version: string;
  generatedAt: string;
  categories: {
    core: {
      description: string;
      symbols: string[];
      subcategories: Record<string, string[]>;
    };
    api: {
      description: string;
      symbols: string[];
      subcategories: Record<string, string[]>;
    };
  };
  symbols: Record<string, ApiSymbol>;
}

// ============================================================================
// Simple AST Parser
// ============================================================================

class SimpleParser {
  private sourceFiles: Map<string, string> = new Map();
  private symbols: Map<string, ApiSymbol> = new Map();

  constructor(entryPoint: string) {
    this.loadSourceFiles(entryPoint);
  }

  private loadSourceFiles(entryPoint: string) {
    const queue: string[] = [entryPoint];
    const visited = new Set<string>();

    while (queue.length > 0) {
      const filePath = queue.shift()!;
      if (visited.has(filePath)) continue;
      visited.add(filePath);

      const fullPath = path.resolve(filePath);
      if (!fs.existsSync(fullPath)) continue;

      const content = fs.readFileSync(fullPath, "utf-8");
      this.sourceFiles.set(fullPath, content);

      // Find import statements to follow
      const importRegex = /export\s+\*\s+from\s+["']([^"']+)["']/g;
      let match;
      while ((match = importRegex.exec(content)) !== null) {
        const importPath = match[1];
        if (!importPath.startsWith(".")) continue; // Skip node_modules
        
        const dirPath = path.dirname(fullPath);
        const resolvedPath = path.resolve(dirPath, importPath);
        
        // Try both .ts file and directory with index.ts
        const possiblePaths = [
          resolvedPath + ".ts",
          path.join(resolvedPath, "index.ts"),
        ];
        
        for (const possiblePath of possiblePaths) {
          if (!visited.has(possiblePath)) {
            queue.push(possiblePath);
          }
        }
      }
    }
  }

  extract(): ApiSymbol[] {
    // Parse entry point
    const entryContent = this.sourceFiles.get(CONFIG.entryPoint);
    if (!entryContent) {
      throw new Error(`Entry point not found: ${CONFIG.entryPoint}`);
    }

    // Find re-exports
    const coreExports = this.parseExports(entryContent, "core");
    const apiExports = this.parseExports(entryContent, "api");

    // Process core exports
    for (const exportName of coreExports) {
      this.processExport(exportName, "core");
    }

    // Process api exports
    for (const exportName of apiExports) {
      this.processExport(exportName, "api");
    }

    return Array.from(this.symbols.values());
  }

  private parseExports(content: string, category: "core" | "api"): string[] {
    const exports: string[] = [];
    
    if (category === "core") {
      // Look for: export * from "./_core";
      const match = content.match(/export\s+\*\s+from\s+["']\.\/_core["']/);
      if (match) {
        const coreIndexPath = path.resolve(path.dirname(CONFIG.entryPoint), "./_core/index.ts");
        const coreContent = this.sourceFiles.get(coreIndexPath);
        if (coreContent) {
          const coreExports = coreContent.match(/export\s+\*\s+from\s+["']\.\/([^"']+)["']/g) || [];
          for (const exp of coreExports) {
            const fileMatch = exp.match(/["']\.\/([^"']+)["']/);
            if (fileMatch) {
              const filePath = path.resolve(path.dirname(coreIndexPath), `${fileMatch[1]}.ts`);
              const fileContent = this.sourceFiles.get(filePath);
              if (fileContent) {
                const names = this.extractExportNames(fileContent);
                exports.push(...names);
              }
            }
          }
        }
      }
    } else {
      // Look for: export * from "./api";
      const match = content.match(/export\s+\*\s+from\s+["']\.\/api["']/);
      if (match) {
        const apiIndexPath = path.resolve(path.dirname(CONFIG.entryPoint), "./api/index.ts");
        const apiContent = this.sourceFiles.get(apiIndexPath);
        if (apiContent) {
          const apiExports = apiContent.match(/export\s+\*\s+from\s+["']\.\/([^"']+)["']/g) || [];
          for (const exp of apiExports) {
            const fileMatch = exp.match(/["']\.\/([^"']+)["']/);
            if (fileMatch) {
              const filePath = path.resolve(path.dirname(apiIndexPath), `${fileMatch[1]}.ts`);
              const fileContent = this.sourceFiles.get(filePath);
              if (fileContent) {
                const names = this.extractExportNames(fileContent);
                exports.push(...names);
              }
            }
          }
        }
      }
    }

    return exports;
  }

  private extractExportNames(content: string): string[] {
    const names: string[] = [];
    
    // export const name = ...
    const constMatches = content.matchAll(/export\s+(?:const|function)\s+(\w+)/g);
    for (const match of constMatches) {
      names.push(match[1]);
    }

    // export type Name = ...
    const typeMatches = content.matchAll(/export\s+(?:type|interface)\s+(\w+)/g);
    for (const match of typeMatches) {
      names.push(match[1]);
    }

    // export class Name
    const classMatches = content.matchAll(/export\s+class\s+(\w+)/g);
    for (const match of classMatches) {
      names.push(match[1]);
    }

    return names;
  }

  private processExport(name: string, category: "core" | "api") {
    const key = `${category}:${name}`;
    if (this.symbols.has(key)) return;

    // Find the file that exports this symbol
    for (const [filePath, content] of this.sourceFiles) {
      if (this.exportsSymbol(content, name)) {
        const apiSymbol: ApiSymbol = {
          name,
          kind: this.determineKind(content, name),
          filePath: filePath.replace(/^\.\//, ""),
          isExported: true,
          isPublic: !CONFIG.excludePatterns.some((pattern) => pattern.test(name)),
          category,
          subcategory: this.determineSubcategory(filePath, category),
        };

        // Extract TSDoc
        apiSymbol.tsdoc = this.parseTSDoc(content, name);

        // Extract type information
        this.extractTypeInfo(content, name, apiSymbol);

        this.symbols.set(key, apiSymbol);
        break;
      }
    }
  }

  private exportsSymbol(content: string, name: string): boolean {
    const patterns = [
      new RegExp(`export\\s+(?:const|function)\\s+${name}\\b`),
      new RegExp(`export\\s+(?:type|interface)\\s+${name}\\b`),
      new RegExp(`export\\s+class\\s+${name}\\b`),
    ];
    return patterns.some((pattern) => pattern.test(content));
  }

  private determineKind(content: string, name: string): string {
    if (new RegExp(`export\\s+const\\s+${name}\\b`).test(content)) return "VariableDeclaration";
    if (new RegExp(`export\\s+function\\s+${name}\\b`).test(content)) return "FunctionDeclaration";
    if (new RegExp(`export\\s+type\\s+${name}\\b`).test(content)) return "TypeAlias";
    if (new RegExp(`export\\s+interface\\s+${name}\\b`).test(content)) return "InterfaceDeclaration";
    if (new RegExp(`export\\s+class\\s+${name}\\b`).test(content)) return "ClassDeclaration";
    return "Unknown";
  }

  private parseTSDoc(content: string, name: string): TSDoc {
    const tsdoc: TSDoc = {};
    
    // Find the export statement with its exact position
    const exportPattern = new RegExp(`export\\s+(?:const|function|type|interface|class)\\s+${name}\\b`);
    const exportMatch = content.search(exportPattern);
    
    if (exportMatch !== -1) {
      // Look backwards from the export to find the immediately preceding JSDoc comment
      const beforeExport = content.substring(0, exportMatch);
      
      // Find the last JSDoc comment that ends with only whitespace before the export
      const jsdocPattern = /\/\*\*([\s\S]*?)\*\//g;
      let match;
      let lastValidMatch = null;
      let lastValidEnd = 0;
      
      while ((match = jsdocPattern.exec(beforeExport)) !== null) {
        const afterJSDoc = beforeExport.substring(match.index + match[0].length);
        // Check if there's only whitespace between this JSDoc and the export
        if (afterJSDoc.trim().length === 0) {
          lastValidMatch = match;
          lastValidEnd = match.index + match[0].length;
        }
      }
      
      if (lastValidMatch) {
        const comment = lastValidMatch[1];
        tsdoc.summary = this.extractSummary(comment);
        tsdoc.remarks = this.extractTag(comment, "remarks");
        tsdoc.returns = this.extractTag(comment, "returns") || this.extractTag(comment, "return");
        tsdoc.deprecated = this.extractTag(comment, "deprecated");
        
        const examples = this.extractAllTags(comment, "example");
        if (examples.length > 0) {
          tsdoc.examples = examples;
        }

        const params = this.extractParams(comment);
        if (params.length > 0) {
          tsdoc.params = params;
        }

        const seeTags = this.extractAllTags(comment, "see");
        if (seeTags.length > 0) {
          tsdoc.see = seeTags;
        }

        const templateTags = this.extractAllTags(comment, "template");
        if (templateTags.length > 0) {
          tsdoc.template = templateTags;
        }
      }
    }

    return tsdoc;
  }

  private extractSummary(comment: string): string {
    // Remove @ tags and their content (multi-line)
    const withoutTags = comment.replace(/@\w+[\s\S]*?(?=@\w|\*$)/g, "").trim();
    // Clean up whitespace and remove leading asterisks
    return withoutTags
      .split("\n")
      .map((line) => line.trim().replace(/^\s*\*\s?/, "").trim())
      .filter((line) => line.length > 0 && !line.startsWith("@"))
      .join("\n");
  }

  private extractTag(comment: string, tagName: string): string | undefined {
    const pattern = new RegExp(`@${tagName}\\s+([\\s\\S]*?)(?=\\n\\s*@\\w+\\s|$)`, "i");
    const match = comment.match(pattern);
    if (match) {
      let content = match[1].trim();
      // Remove trailing whitespace and asterisks
      content = content.replace(/[\s\*]*$/, "");
      return content
        .split("\n")
        .map((line) => line.trim().replace(/^\s*\*\s?/, "").trim())
        .filter((line) => line.length > 0 && !line.startsWith("@"))
        .join("\n");
    }
    return undefined;
  }

  private extractAllTags(comment: string, tagName: string): string[] {
    const pattern = new RegExp(`@${tagName}\\s+([\\s\\S]*?)(?=\\n\\s*@\\w+\\s|$)`, "gi");
    const matches = comment.matchAll(pattern);
    return Array.from(matches).map((m) => {
      let content = m[1].trim();
      // Remove trailing whitespace and asterisks
      content = content.replace(/[\s\*]*$/, "");
      return content
        .split("\n")
        .map((line) => line.trim().replace(/^\s*\*\s?/, "").trim())
        .filter((line) => line.length > 0 && !line.startsWith("@"))
        .join("\n");
    });
  }

  private extractParams(comment: string): ParamTag[] {
    const params: ParamTag[] = [];
    const pattern = /@param\s+(\w+)\s*-?\s*([\s\S]*?)(?=\n\s*@|$)/gi;
    let match;
    while ((match = pattern.exec(comment)) !== null) {
      const description = match[2]
        .trim()
        .split("\n")
        .map((line) => line.trim().replace(/^\s*\*\s?/, "").trim())
        .filter((line) => line.length > 0 && !line.startsWith("@"))
        .join("\n");
      params.push({ name: match[1], description });
    }
    return params;
  }

  private extractTypeInfo(content: string, name: string, apiSymbol: ApiSymbol) {
    // Extract function signature
    const funcPattern = new RegExp(`export\\s+(?:const|function)\\s+${name}\\s*(?:<[^>]+>)?\\s*\\(([^)]*)\\)\\s*(?::\\s*([^\\n;]+))?`);
    const funcMatch = content.match(funcPattern);
    
    if (funcMatch) {
      apiSymbol.signature = funcMatch[0];
      apiSymbol.returnType = funcMatch[2] || "void";
      
      // Extract parameters
      const paramsStr = funcMatch[1];
      if (paramsStr.trim()) {
        const paramPattern = /(\w+)(\?)?:\s*([^,=]+)/g;
        let paramMatch;
        const parameters: Parameter[] = [];
        while ((paramMatch = paramPattern.exec(paramsStr)) !== null) {
          parameters.push({
            name: paramMatch[1],
            type: paramMatch[3].trim(),
            isOptional: paramMatch[2] === "?",
          });
        }
        apiSymbol.parameters = parameters;
      }

      // Extract type parameters
      const typeParamPattern = new RegExp(`${name}\\s*<([^>]+)>`);
      const typeParamMatch = content.match(typeParamPattern);
      if (typeParamMatch) {
        const typeParams = typeParamMatch[1].split(",").map((tp) => tp.trim());
        apiSymbol.typeParameters = typeParams.map((tp) => {
          const parts = tp.split("=");
          const name = parts[0].trim();
          const constraintMatch = name.match(/(\w+)\s+extends\s+(.+)/);
          if (constraintMatch) {
            return {
              name: constraintMatch[1],
              constraint: constraintMatch[2].trim(),
              default: parts[1]?.trim(),
            };
          }
          return {
            name,
            default: parts[1]?.trim(),
          };
        });
      }
    }

    // Extract type alias
    const typePattern = new RegExp(`export\\s+type\\s+${name}\\s*(?:<[^>]+>)?\\s*=\\s*([^\\n;]+)`);
    const typeMatch = content.match(typePattern);
    if (typeMatch) {
      apiSymbol.type = typeMatch[1].trim();
    }

    // Extract interface
    const interfacePattern = new RegExp(`export\\s+interface\\s+${name}\\s*(?:<[^>]+>)?\\s*\\{([\\s\\S]*?)\\n\\}`);
    const interfaceMatch = content.match(interfacePattern);
    if (interfaceMatch) {
      apiSymbol.type = `interface ${name} { ... }`;
    }
  }

  private determineSubcategory(filePath: string, category: "core" | "api"): string | undefined {
    const relativePath = filePath.replace(process.cwd(), "");
    
    // Extract the directory name from the file path
    // e.g., /Users/ck/Desktop/packages/signal/src/_core/signal/source-signal.ts -> signal
    // e.g., /Users/ck/Desktop/packages/signal/src/_core/utils/type-checkers.ts -> utils
    
    if (relativePath.includes("/utils/") && !relativePath.endsWith("/utils/index.ts")) return "utils";
    if (relativePath.includes("/signal/") && !relativePath.endsWith("/signal/index.ts")) return "signal";
    if (relativePath.includes("/traps/") && !relativePath.endsWith("/traps/index.ts")) return "traps";
    if (relativePath.includes("/operations/") && !relativePath.endsWith("/operations/index.ts")) return "operations";
    
    // Check if it's in a subdirectory (not index.ts)
    const pathParts = relativePath.split("/").filter(p => p);
    if (pathParts.length >= 4) {
      const fileName = pathParts[pathParts.length - 1];
      if (fileName !== "index.ts") {
        return pathParts[pathParts.length - 2];
      }
    }
    
    return undefined;
  }
}

// ============================================================================
// Markdown Generator
// ============================================================================

class MarkdownGenerator {
  static generate(symbol: ApiSymbol): string {
    const lines: string[] = [];
    
    // Generated notice
    lines.push(CONFIG.generatedNotice);
    lines.push("");

    // Title
    const title = this.formatTitle(symbol.name);
    lines.push(`# ${title}`);
    lines.push("");

    // Summary
    if (symbol.tsdoc?.summary) {
      lines.push(symbol.tsdoc.summary);
      lines.push("");
    }

    // Type signature
    if (symbol.type) {
      lines.push("## Type");
      lines.push("");
      lines.push("```typescript");
      lines.push(symbol.type);
      lines.push("```");
      lines.push("");
    }

    // Function signature
    if (symbol.signature) {
      lines.push("## Signature");
      lines.push("");
      lines.push("```typescript");
      lines.push(symbol.signature);
      lines.push("```");
      lines.push("");
    }

    // Type parameters
    if (symbol.typeParameters && symbol.typeParameters.length > 0) {
      lines.push("## Type Parameters");
      lines.push("");
      for (const tp of symbol.typeParameters) {
        let line = `- \`${tp.name}\``;
        if (tp.constraint) line += ` extends \`${tp.constraint}\``;
        if (tp.default) line += ` = \`${tp.default}\``;
        lines.push(line);
      }
      lines.push("");
    }

    // Parameters
    if (symbol.parameters && symbol.parameters.length > 0) {
      lines.push("## Parameters");
      lines.push("");
      for (const param of symbol.parameters) {
        let line = `- **${param.name}**: \`${param.type}\``;
        if (param.isOptional) line += " (optional)";
        lines.push(line);
      }
      lines.push("");
    }

    // Return type
    if (symbol.returnType) {
      lines.push("## Returns");
      lines.push("");
      lines.push(`\`${symbol.returnType}\``);
      lines.push("");
    }

    // Remarks
    if (symbol.tsdoc?.remarks) {
      lines.push("## Remarks");
      lines.push("");
      lines.push(symbol.tsdoc.remarks);
      lines.push("");
    }

    // Examples
    if (symbol.tsdoc?.examples && symbol.tsdoc.examples.length > 0) {
      lines.push("## Examples");
      lines.push("");
      for (const example of symbol.tsdoc.examples) {
        lines.push(example);
        lines.push("");
      }
    }

    // See also
    if (symbol.tsdoc?.see && symbol.tsdoc.see.length > 0) {
      lines.push("## See Also");
      lines.push("");
      for (const see of symbol.tsdoc.see) {
        lines.push(`- ${see}`);
      }
      lines.push("");
    }

    // Deprecated
    if (symbol.tsdoc?.deprecated) {
      lines.push("## Deprecated");
      lines.push("");
      lines.push(`> ${symbol.tsdoc.deprecated}`);
      lines.push("");
    }

    // Source file reference
    lines.push("---");
    lines.push("");
    lines.push(`*Source: [${symbol.filePath}](${symbol.filePath})*`);

    return lines.join("\n");
  }

  private static formatTitle(name: string): string {
    // Convert camelCase to Title Case with spaces
    return name
      .replace(/([a-z])([A-Z])/g, "$1 $2")
      .replace(/^./, (char) => char.toUpperCase());
  }

  static slugify(name: string): string {
    return name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/(^-|-$)/g, "");
  }
}

// ============================================================================
// Metadata Generator
// ============================================================================

class MetadataGenerator {
  static generate(symbols: ApiSymbol[]): ApiMetadata {
    const metadata: ApiMetadata = {
      version: "1.0.0",
      generatedAt: new Date().toISOString(),
      categories: {
        core: {
          description: "Core reactive primitives and utilities",
          symbols: [],
          subcategories: {},
        },
        api: {
          description: "Higher-level convenience APIs",
          symbols: [],
          subcategories: {},
        },
      },
      symbols: {},
    };

    for (const symbol of symbols) {
      const key = `${symbol.category}:${symbol.name}`;
      metadata.symbols[key] = symbol;

      if (symbol.category === "core") {
        metadata.categories.core.symbols.push(symbol.name);
        if (symbol.subcategory) {
          if (!metadata.categories.core.subcategories[symbol.subcategory]) {
            metadata.categories.core.subcategories[symbol.subcategory] = [];
          }
          metadata.categories.core.subcategories[symbol.subcategory].push(symbol.name);
        }
      } else {
        metadata.categories.api.symbols.push(symbol.name);
        if (symbol.subcategory) {
          if (!metadata.categories.api.subcategories[symbol.subcategory]) {
            metadata.categories.api.subcategories[symbol.subcategory] = [];
          }
          metadata.categories.api.subcategories[symbol.subcategory].push(symbol.name);
        }
      }
    }

    return metadata;
  }
}

// ============================================================================
// File System Operations
// ============================================================================

class FileSystem {
  static ensureDir(dirPath: string) {
    if (!fs.existsSync(dirPath)) {
      fs.mkdirSync(dirPath, { recursive: true });
    }
  }

  static cleanDir(dirPath: string) {
    if (fs.existsSync(dirPath)) {
      fs.rmSync(dirPath, { recursive: true, force: true });
    }
    this.ensureDir(dirPath);
  }

  static writeFile(filePath: string, content: string) {
    const dir = path.dirname(filePath);
    this.ensureDir(dir);
    fs.writeFileSync(filePath, content, "utf-8");
  }
}

// ============================================================================
// Main Generator
// ============================================================================

async function main() {
  console.log("🔍 Extracting API symbols from source code...");
  const parser = new SimpleParser(CONFIG.entryPoint);
  const symbols = parser.extract();

  console.log(`✓ Found ${symbols.length} public symbols`);

  console.log("🧹 Cleaning output directory...");
  FileSystem.cleanDir(CONFIG.outputDir);

  console.log("📝 Generating markdown files...");
  for (const symbol of symbols) {
    if (!symbol.isPublic) continue;

    const markdown = MarkdownGenerator.generate(symbol);
    const slug = MarkdownGenerator.slugify(symbol.name);
    
    let filePath: string;
    if (symbol.category === "core") {
      if (symbol.subcategory) {
        filePath = path.join(CONFIG.outputDir, symbol.category, symbol.subcategory, `${slug}.md`);
      } else {
        filePath = path.join(CONFIG.outputDir, symbol.category, `${slug}.md`);
      }
    } else {
      if (symbol.subcategory) {
        filePath = path.join(CONFIG.outputDir, symbol.category, symbol.subcategory, `${slug}.md`);
      } else {
        filePath = path.join(CONFIG.outputDir, symbol.category, `${slug}.md`);
      }
    }

    FileSystem.writeFile(filePath, markdown);
    console.log(`  ✓ Generated: ${filePath}`);
  }

  console.log("📋 Generating metadata...");
  const metadata = MetadataGenerator.generate(symbols);
  FileSystem.writeFile(
    path.join(CONFIG.outputDir, "_meta.json"),
    JSON.stringify(metadata, null, 2)
  );
  console.log(`  ✓ Generated: ${path.join(CONFIG.outputDir, "_meta.json")}`);

  console.log("✅ API documentation generation complete!");
  console.log(`📁 Output directory: ${CONFIG.outputDir}`);
}

// Run the generator
main().catch((error) => {
  console.error("❌ Error generating API documentation:", error);
  process.exit(1);
});
